//
//  CatalogView.swift
//  VibeCoder
//
//  The home/catalog screen. Lists the 30 curated lessons grouped by
//  difficulty, no live network calls, no user-generated content shown.
//

import SwiftUI

struct CatalogView: View {
    @StateObject private var store = CatalogStore.shared
    @State private var selectedDifficulty: Difficulty? = nil

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    headerSection
                    if let err = store.loadError {
                        Text(err)
                            .font(.callout)
                            .foregroundStyle(.red)
                            .padding(.horizontal)
                    }
                    difficultyFilter
                    ForEach(difficultiesToShow) { diff in
                        let items = store.projects(in: diff)
                        if !items.isEmpty {
                            section(diff: diff, items: items)
                        }
                    }
                    Spacer(minLength: 60)
                }
                .padding(.top, 12)
            }
            .background(Color.black.ignoresSafeArea())
            .preferredColorScheme(.dark)
            .navigationTitle("Lessons")
            .navigationBarTitleDisplayMode(.inline)
        }
    }

    private var difficultiesToShow: [Difficulty] {
        if let s = selectedDifficulty { return [s] }
        return Difficulty.allCases
    }

    private var headerSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Learn how AI builds apps")
                .font(.title.bold())
                .foregroundStyle(.white)
            Text("Read the source code of real web apps generated by AI. Edit them, see how they work, and follow the structure to build your own.")
                .font(.callout)
                .foregroundStyle(.white.opacity(0.7))
        }
        .padding(.horizontal)
    }

    private var difficultyFilter: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 8) {
                chip("All", selected: selectedDifficulty == nil) { selectedDifficulty = nil }
                ForEach(Difficulty.allCases) { d in
                    chip(d.rawValue, selected: selectedDifficulty == d) {
                        selectedDifficulty = selectedDifficulty == d ? nil : d
                    }
                }
            }
            .padding(.horizontal)
        }
    }

    private func chip(_ label: String, selected: Bool, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Text(label)
                .font(.subheadline.weight(selected ? .semibold : .regular))
                .padding(.horizontal, 14)
                .padding(.vertical, 8)
                .foregroundStyle(selected ? .black : .white)
                .background(
                    Capsule().fill(selected ? Color.white : Color.white.opacity(0.10))
                )
        }
        .buttonStyle(.plain)
    }

    private func section(diff: Difficulty, items: [CatalogProject]) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(diff.rawValue)
                    .font(.title3.bold())
                    .foregroundStyle(.white)
                Spacer()
                Text("\(items.count)")
                    .font(.caption.monospacedDigit())
                    .foregroundStyle(.white.opacity(0.5))
            }
            .padding(.horizontal)
            LazyVStack(spacing: 10) {
                ForEach(items) { p in
                    NavigationLink(value: p) {
                        LessonCard(project: p)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.horizontal)
        }
        .navigationDestination(for: CatalogProject.self) { project in
            LessonDetailView(project: project)
        }
    }
}

struct LessonCard: View {
    let project: CatalogProject

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            ZStack {
                RoundedRectangle(cornerRadius: 10)
                    .fill(LinearGradient(colors: gradientColors,
                                         startPoint: .topLeading,
                                         endPoint: .bottomTrailing))
                    .frame(width: 64, height: 64)
                Image(systemName: iconName)
                    .font(.title2)
                    .foregroundStyle(.white)
            }
            VStack(alignment: .leading, spacing: 4) {
                Text(project.title)
                    .font(.body.weight(.semibold))
                    .foregroundStyle(.white)
                    .lineLimit(2)
                    .multilineTextAlignment(.leading)
                Text(project.category)
                    .font(.caption)
                    .foregroundStyle(.white.opacity(0.55))
                HStack(spacing: 8) {
                    Label("\(project.fileCount) \(project.fileCount == 1 ? "file" : "files")",
                          systemImage: "doc.text")
                        .font(.caption2)
                        .foregroundStyle(.white.opacity(0.5))
                    if !project.creator.isEmpty {
                        Text("·")
                            .foregroundStyle(.white.opacity(0.3))
                        Text(project.creator)
                            .font(.caption2)
                            .foregroundStyle(.white.opacity(0.5))
                            .lineLimit(1)
                    }
                }
                .padding(.top, 2)
            }
            Spacer(minLength: 0)
            Image(systemName: "chevron.right")
                .font(.caption.weight(.semibold))
                .foregroundStyle(.white.opacity(0.3))
        }
        .padding(12)
        .background(
            RoundedRectangle(cornerRadius: 14)
                .fill(Color.white.opacity(0.06))
        )
    }

    private var iconName: String {
        switch project.category {
        case "Games & Canvas": return "gamecontroller.fill"
        case "Mobile UIs": return "iphone"
        case "Productivity": return "checkmark.circle.fill"
        case "Layouts": return "rectangle.3.group"
        case "Forms & Input": return "square.and.pencil"
        case "Visual / Animation": return "wand.and.stars"
        case "Finance": return "dollarsign.circle.fill"
        default: return "doc.text"
        }
    }

    private var gradientColors: [Color] {
        switch project.difficulty {
        case "Beginner": return [Color(red: 0.31, green: 0.78, blue: 0.47), Color(red: 0.16, green: 0.51, blue: 0.30)]
        case "Intermediate": return [Color(red: 0.31, green: 0.51, blue: 0.95), Color(red: 0.55, green: 0.28, blue: 0.85)]
        default: return [Color(red: 0.95, green: 0.42, blue: 0.31), Color(red: 0.78, green: 0.16, blue: 0.30)]
        }
    }
}
